version: '3'
services:
  serve:
    image: jekyll/jekyll:latest
    command: /bin/bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch --verbose --trace"
    working_dir: /app
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - 4000:4000

  build:
    image: jekyll/jekyll:latest
    command: /bin/bash -c "bundle install && bundle exec jekyll build"
    working_dir: /app
    volumes:
      - .:/app
      - gems:/usr/local/bundle

volumes:
  gems:
