version: '3'
services:
  jekyll:
    image: jekyll/jekyll:latest
    command: /bin/bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch --verbose --trace"
    working_dir: /app
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - 4000:4000

volumes:
  gems:
